// -*- c++ -*-
// Author: Sebastian Bronte Palacios. sebastian.bronte@depeca.uah.es
//
// TrackWriter.h
//
// Defines the TrackWriter class
//
// This writes to disk feature coordinates, camera poses and some extra data generated by the
// tracker thread, which can be loaded from other applications to work on it.
//

#ifndef __TRACK_WRITER_H
#define __TRACK_WRITER_H

#include <TooN/TooN.h>
using namespace TooN;
#include <TooN/se3.h>
#include <TooN/so3.h>
#include <cvd/image.h>
#include <fstream>
#include <vector>

//class VisualNRTracker;
//class NRTracker;
class AbstractTracker;

class TrackWriter
{
public:
  TrackWriter(AbstractTracker &track);
  ~TrackWriter();

  void writeToDisk();
  void saveCurrentFrameData();

protected:
  //reference to Tracker object. It contains the pose of the cammera and some
  //useful tracker data, including the coefficients of non rigid shapes.
  AbstractTracker &mTracker;
  std::string filename_featurepoints; //full filename for feature points file
  std::string filename_poses; //full filename for tracker poses file
  std::string filename_quality; //full filename for tracker poses file
  std::string filename_coeffs; //full filename for coefficients file
  std::string filename_raw;

  //map tracking features
  std::vector< Vector<2> > buffer_featurepoints;
  std::vector<unsigned int> buffer_nfeaturesperframe;
  std::vector< SE3<> > buffer_poses;
  std::vector<double> buffer_pointindex;
  std::vector< Vector<2> > buffer_pointcovariance;
  std::vector<bool> buffer_found;
  std::vector<int> buffer_level;
  std::vector<int> buffer_quality;
  std::vector< std::vector<double> > buffer_coeffs;
  std::vector<bool> buffer_outliers;
  std::vector<Vector<3> > buffer_3dpoints;
  //raw tracking features
  std::vector< CVD::ImageRef > buffer_featurepoints_raw;
  std::vector<int> buffer_level_raw;
  std::vector<unsigned int> buffer_nfeaturesperframe_raw;

  //files
  std::ofstream outfile1; //stream to the feature points file
  std::ofstream outfile2; //stream to the tracker poses file
  std::ofstream outfile3; //stream to the tracker quality file

  std::ofstream outfile4; //stream to the raw tracker data file
  std::ofstream outfile5; //stream to the coefficients file.

};

#endif
